// <auto-generated />
namespace pastexamRAD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _8thmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_8thmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202101111453241_8th migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
